# Generated by Django 4.2.2 on 2023-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.CharField(max_length=300, verbose_name='가족관계증명서')),
                ('file2', models.CharField(max_length=300, verbose_name='주민등록등본')),
                ('file3', models.CharField(max_length=300, verbose_name='장애인등록증')),
                ('file4', models.CharField(max_length=300, verbose_name='정부기관심사결과지')),
            ],
        ),
    ]
