# Generated by Django 4.2.4 on 2023-08-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, upload_to='', verbose_name='가족관계증명서')),
                ('file2', models.FileField(blank=True, upload_to='', verbose_name='주민등록등본')),
                ('file3', models.FileField(blank=True, upload_to='', verbose_name='장애인등록증')),
                ('file4', models.FileField(blank=True, upload_to='', verbose_name='정부기관심사결과지')),
                ('user', models.ForeignKey(default='2966447342', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
