# Generated by Django 4.2.4 on 2023-08-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydocument',
            name='user',
        ),
        migrations.AlterField(
            model_name='mydocument',
            name='file1',
            field=models.CharField(max_length=300, verbose_name='가족관계증명서'),
        ),
        migrations.AlterField(
            model_name='mydocument',
            name='file2',
            field=models.CharField(max_length=300, verbose_name='주민등록등본'),
        ),
        migrations.AlterField(
            model_name='mydocument',
            name='file3',
            field=models.CharField(max_length=300, verbose_name='장애인등록증'),
        ),
        migrations.AlterField(
            model_name='mydocument',
            name='file4',
            field=models.CharField(max_length=300, verbose_name='정부기관심사결과지'),
        ),
    ]
