# Generated by Django 4.2.4 on 2023-08-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='소셜사용자_id')),
                ('social_type', models.CharField(max_length=20, verbose_name='소셜 타입')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='이름')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='전화번호')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일자')),
                ('age_range', models.CharField(blank=True, max_length=10, null=True, verbose_name='연령대')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='성별')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
