# Generated by Django 4.2.2 on 2023-08-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='이미지')),
                ('title', models.CharField(max_length=20, verbose_name='프로그램명')),
                ('district', models.CharField(max_length=11, verbose_name='지역')),
                ('agency', models.CharField(max_length=15, verbose_name='기관')),
                ('deadline_yy', models.IntegerField(verbose_name='마감일 연')),
                ('deadline_mm', models.IntegerField(verbose_name='마감일 월')),
                ('deadline_dd', models.IntegerField(verbose_name='마감일 일')),
                ('phone', models.CharField(max_length=13, verbose_name='문의처')),
                ('like', models.IntegerField(default=0, verbose_name='좋아요 개수')),
                ('iflike', models.BooleanField(default=False, verbose_name='좋아요 여부')),
                ('category1', models.CharField(max_length=20, verbose_name='카테고리1')),
                ('category2', models.CharField(max_length=20, verbose_name='카테고리2')),
                ('applicant', models.IntegerField(default=15, verbose_name='신청 가능 인원')),
            ],
        ),
        migrations.CreateModel(
            name='MyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='MyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
