# Generated by Django 4.2.4 on 2023-08-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprogram',
            name='process',
        ),
    ]
