# Generated by Django 4.2.2 on 2023-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='deadline_dd',
            field=models.CharField(max_length=2, verbose_name='마감일 일'),
        ),
        migrations.AlterField(
            model_name='program',
            name='deadline_mm',
            field=models.CharField(max_length=2, verbose_name='마감일 월'),
        ),
    ]
